### ISSUE TITLE
MultiSelectField

### ISSUE THREAD

**Issue by DamienIrving** [resbaz/workshop-data-management#1]
I've installed MultiSelectField (`pip install django-multiselectfield`) and used it for participant dietary requirement choices and person teaching team choices. There are bugs with the implementation of both:
- _teaching team:_ I'm able to successfully create and save a participant with more than one teaching team but if I try and filter by teaching team (in `admin.py`) it throws an error
- _dietary requirement:_ I'm unable to successfully create and save a participant with more than one dietary requirement

**Comment by lachlansimpson** [comment]
Hmmm. Interesting.  I was just thinking about this problem in the shower.
Send me the code and the error for starters.

But I think, and this is going to sound hokey, that your best best is a
list of booleans on the object: the multi select part is merely UI/UX.
Storage is essentially y/n 1/0.

Does that seem reasonable? An m2m is overkill for dietary, since we need no
extra info on its data.

Give me a teaching team eg?

Cheers
L.

**Comment by datakid** [comment]
Sorry, am at cafe atm. Yesterday got derailed by my lover, hence the radio
silence.

**Comment by lachlansimpson** [comment]
The other option, of course, is to use something like django taggit to tag
people w their dietary needs. Again, in the UI they only see a reduced set
of selections, and we do the work in the object creation to translate their
choice from a radio button to a tag...

**Comment by DamienIrving** [comment]
@datakid No need to apologise - it is the weekend after all! I'm just documenting the bugs in issues like this so I don't forget them.

If you clone the latest version of the master branch, pip install django-multiselectfield and then try and add a new participant with multiple dietary requirements you'll be able to re-create the error. If you crack that error, next try and define a dietary requirement filter in `admin.py`\- that will re-create the other error.

**Comment by DamienIrving** [comment]
Ah, yes - I'm also very open to other options like taggit as opposed to MultiSelectField (in my naive google searching MultiSelectField come up a lot, but I was hoping you might know of a better way!)

**Comment by lachlansimpson** [comment]
I think the best solution is a group of booleans on the object, for a
fairly static group. For a non static group, the taggit solution is
probably best since it doesn't require a db migration.

**Comment by DamienIrving** [comment]
We went with the booleans approach.
