### ISSUE TITLE
Dependent choice fields

### ISSUE THREAD

**Issue by DamienIrving** [resbaz/workshop-data-management#2]
I'd like to allow one choice field to depend on another (e.g. once I've selected my home institution the campus choices should only include those associated with that home institution). It looks like `smart_selects` (`pip install django-smart-selects`; see documentation [here](https://github.com/digi604/django-smart-selects)) might be the library to use, however from their examples I can't figure out how I'd implement it. In particular, I don't have an institution class, just lists of institution/campus/department choices, and their examples seem to depend on having actual classes for these things.

Since I don't think we need an institution class (a list should suffice), another thought is that you can collect choices into named groups (see example [here](https://docs.djangoproject.com/en/1.7/ref/models/fields/#django.db.models.Field.choices)). Perhaps that is the way forward?

**Comment by lachlansimpson** [comment]
Yes. I was thinking about this too. The only issue is that the resulting
data (to use the example) would say vhs not video or video:vhs. So the db
owner/interface would need to interpolate. Not the end of the world and
very doable, but undeniably a little awkward.

I'm shocked that we've managed to find two awkward use cases almost
immediately.

Keep in mind the diff between data stored (sql, django model) and data
representation (usually html/css/js).

Like any good fashion mag, html/css/js can make _anything_ look how you
want. And python can manipulate the data to present it.

**Comment by DamienIrving** [comment]
The solution was simply to create an institution class.
